name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  MIX_ENV: test

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1
        with:
          otp-version: "28.4"
          elixir-version: "1.20.2"

      - name: Restore deps cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: deps-${{ runner.os }}-

      - name: Restore PLT cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: priv/plts
          key: plts-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: plts-${{ runner.os }}-

      - name: Install deps
        run: mix deps.get

      - name: "Hex Audit"
        run: mix hex.audit

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Check formatting
        run: mix format --check-formatted

      - name: Credo
        run: mix credo --all --strict

      - name: Dialyzer
        run: mix dialyzer

      - name: Run tests
        run: mix test
